baseURL = "https://dtolpin.github.io/"
languageCode = "en-us"
title = "Offtopia â€” nothing personal"
theme = "offtopia"

# Pagination
summaryLength = 50
pagination.pageSize = 5

[permalinks]
	posts = "/:year/:month/:title/"
	page = "/:slug/"

[[menu.navbar]]
    url = "/about/"
    name = "About"
    weight = 2
[[menu.navbar]]
	url = "/academic/"
	name = "Academic"
	weight = 3

[[menu.sidebar]]
	url = "https://infergo.org/"
	name = "Infergo"
	weight = 4
[[menu.sidebar]]
	url = "https://offtopia.net/wp/"
	name = "Old blog"
	weight = 5

[params]
    author = "David Tolpin"
    date_format = "Mon Jan 02, 2006"

	[params.sidebar]
	placeholder = "" # otherwise does not display recent posts
